language: java
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS TaskManagerDB;'

env:
  global:
    - CC_TEST_REPORTER_ID=f2872133aec3ae9fffa50afbafa06f84b7f12546b35059f3a98493a0b68b11ec
    - CODECOV_TOKEN="73807907-de2b-4fa0-b2d6-b4d3210c8ac1"
test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi


before_script:
  - chmod +x ./gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)
